#!/usr/bin/env bash
set -euo pipefail

APP="rdesq"
ARCH="x86_64"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RELEASE_DIR="$SCRIPT_DIR/../src-tauri/target/release"
BINARY="$RELEASE_DIR/$APP"
VERSION="$(jq -r '.version' "$SCRIPT_DIR/../src-tauri/tauri.conf.json")"
APPDIR="$RELEASE_DIR/$APP.AppDir"
OUTDIR="$RELEASE_DIR/bundle/appimage"

echo "[*] Creating AppImage for $APP v$VERSION"

# Download tools
QUICK_SHARUN="$RELEASE_DIR/quick-sharun.sh"
echo "[*] Downloading quick-sharun.sh..."
wget -qO "$QUICK_SHARUN" \
  "https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/main/useful-tools/quick-sharun.sh"
chmod +x "$QUICK_SHARUN"

APPIMAGETOOL="$RELEASE_DIR/appimagetool"
echo "[*] Downloading appimagetool..."
wget -qO "$APPIMAGETOOL" \
  "https://github.com/pkgforge-dev/appimagetool/releases/latest/download/appimagetool-$ARCH-linux"
chmod +x "$APPIMAGETOOL"

# Find desktop file generated by Tauri build
DESKTOP="$(find "$RELEASE_DIR" -name '*.desktop' 2>/dev/null | head -1 || true)"

# Find icon
ICON="$(find "$SCRIPT_DIR/../src-tauri/icons" -name '128x128.png' 2>/dev/null | head -1 || true)"
if [ -z "$ICON" ]; then
  ICON="$(find "$SCRIPT_DIR/../src-tauri/icons" -name '*.png' 2>/dev/null | head -1 || true)"
fi

# Step 1: Create AppDir with bundled dependencies
echo "[*] Bundling dependencies with quick-sharun..."
export DESKTOP ICON APPDIR
export DEPLOY_OPENGL=1
bash "$QUICK_SHARUN" "$BINARY"

# Bundle sshpass for password-based SSH connections
if command -v sshpass &>/dev/null; then
  echo "[*] Bundling sshpass..."
  mkdir -p "$APPDIR/shared/bin"
  cp "$(command -v sshpass)" "$APPDIR/shared/bin/"
  ln -sf ../sharun "$APPDIR/bin/sshpass" 2>/dev/null || true
  for lib in $(ldd "$(command -v sshpass)" 2>/dev/null | grep "=> /" | awk '{print $3}'); do
    mkdir -p "$APPDIR/lib"
    cp -n "$lib" "$APPDIR/lib/" 2>/dev/null || true
  done
fi

# Step 2: Create AppImage from AppDir
echo "[*] Creating AppImage with appimagetool..."
mkdir -p "$OUTDIR"
"$APPIMAGETOOL" "$APPDIR" \
  --output "$OUTDIR" \
  --name "${APP}_${VERSION}_${ARCH}.AppImage"

echo "[+] AppImage created: $OUTDIR/${APP}_${VERSION}_${ARCH}.AppImage"
ls -lh "$OUTDIR"/*.AppImage
